### ISSUE TITLE
avy copy lines from other buffers

### ISSUE THREAD

**Issue by haditim** [karthink/.emacs.d#2]
Hello and thanks for your videos and publishing your configs.

I was following one of your videos at https://www.youtube.com/watch?v=tF4OdtSuXMg and saw that you use `M-s y` for copying lines from other buffers into the current one (time `07:00`). Searching your configs, I see that this is bound to `avy-copy-line`. But I am not able to get it to work among all open buffers and I don't see any other config in your repo that would change the behavior of this. Out of curiosity, how do you make it work like that? For me, only lines from the active buffer can be copied.

Thanks in advance. Also feel free to close the issue. I just opened it here for others searching for this.

**Comment by karthink** [comment]
@haditim Wow that's some crazy attention to detail!

The variable(s) you're looking for probably `avy-all-windows` and `avy-all-windows-alt`. Try `M-x customize-group⮐` `avy` for details.

**Comment by haditim** [comment]
Thanks a lot for the reply and the help. Yes, `avy-all-windows` was the variable that was `nil` for me.

Nice write-up. I should read all of your posts. I also look forward to see more Emacs videos, especially on your daily workflow.

Thanks again.
