### ISSUE TITLE
Trouble when setting `outline-cycle-emulate-tab` to a non-nil value

### ISSUE THREAD

**Issue by apc** [karthink/.emacs.d#3]
I just copied the code in your `setup-folds.el` verbatim to try it out, but I seem to get into trouble when setting `outline-cycle-emulate-tab` to `t`. I guess the problem is [here](https://github.com/karthink/.emacs.d/blob/b4f423806352604a7979656346f5ec516f52863a/lisp/setup-folds.el#L64)? If `outline-cycle-emulate-tab` is non-nil, then this

    (call-interactively (key-binding (vector last-input-event)))

should get us into a loop, unless `outline-minor-mode` is disabled first?

Maybe I'm missing something though?

Thanks for making your config public, by the way. I've learned a great deal from it!

**Comment by karthink** [comment]
Wow I didn't think anyone actually read my init files, they're quite shabby and often in states of disrepair!

> I guess the problem is here? If outline-cycle-emulate-tab is non-nil...

I've never used `outline-cycle-emulate-tab`, I think it's a holdover from when I copied this function (most likely from @alphapapa).  Instead I've modified the `t` block of the cond so the emulate-tab behavior is always active when not at a headline.  (Hence "shabby")

I'm not sure if the built-in outline-cycle or the outshine package lets you do this.  My tab key does six or seven things at this point depending on context.

> Thanks for making your config public, by the way. I've learned a great deal from it!

Glad to hear.  Be careful though, it dates back a couple of decades and is lined with jank.
